apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-logs-pvc
  namespace: subtrack
  labels:
    app: subtrack
    component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
