apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: subtrack
  labels:
    app: subtrack
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: subtrack
    component: frontend
