apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: subtrack
  namespace: argocd
spec:
  project: default 
  source: 
    repoURL: 'https://github.com/Aditya-k-11/sub_tracker.git'
    path: k8s/base
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: subtrack
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions: 
      - CreateNamespace=true


