apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: subtrack
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.email: "adityakanojia.ad@gmail.com"
    notifications.argoproj.io/subscribe.on-crashed.email: "adityakanojia.ad@gmail.com"
spec:
  project: default
  source:
    repoURL: git://host.docker.internal/subtrack
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: subtrack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: backend
      jsonPointers:
        - /spec/replicas
