apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: subtrack

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongo/pvc.yaml
  - mongo/deployment.yaml
  - mongo/service.yaml
  - backend/logs-pvc.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/cronjob.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - ingress/ingress.yaml
